

// Post Request to add new User
POST http://localhost:3001/api/users
Content-Type: application/json


{
    "firstname": "Lavar",
    "lastname": "password",
    "email": "email@email.net"
}



###

// Post request to add new recipe to database
POST http://localhost:3000/api/recipes
Content-Type: application/json

{
"title": "Classic Stuffed Mushrooms",
"categoryId": 1,
"mainIngredient": "mushrooms",
"ingredients": "walnuts, herbs, garlic, chopped mushroom stems, breadcrumbs, grated parmesean",
"directions": "Separate the stems from the mushroom caps and chop them. Process with herbs and breadcrumbs and stuff the mushroom caps with the mixture. Sprinkle with parmesan and bake until the cheese starts to brown and the mushroom caps release some of their water.",
"likes": 2,
"userId": 1
}




###
// Post request to add new comments to database
POST http://localhost:3000/api/comments
Content-Type: application/json

{
"recipeId": 2,
"text": "It's good. Really it's the best thing ever. ",
"user_id": "5e30ac3f73425c236038686c"
}


###


// Post Request to add new category to database
POST http://localhost:3001/api/categories
Content-Type: application/json

{
"title": "dessert"
}