# Using this file requires the VS Code REST Client extension: https://marketplace.visualstudio.com/items?itemName=humao.rest-client

// Post Request to add new User
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "firstname": "aruna",
    "lastname": "password1",
    "email": "email@gmail.net"
}

###

// Post request to add new recipe to database
POST http://localhost:3001/api/recipes
Content-Type: application/json

{
    "title": "Classic Stuffed Mushrooms",
    "category": "entree",
    "ingredients": [
        "walnuts",
        "herbs",
        " garlic",
        "chopped mushroom stems",
        "breadcrumbs",
        "grated parmesean"
    ],
    "directions": "Separate the stems from the mushroom caps and chop them. Process with herbs and breadcrumbs and stuff the mushroom caps with the mixture. Sprinkle with parmesan and bake until the cheese starts to brown and the mushroom caps release some of their water.",
    "likes": 2,
    "user": {
        "firstname": "Levar",
        "lastname": "Burton"
    },
    "comments": [
        {
            "user": "Lavar",
            "text": "I love it"
        },
        {
            "user": "Jon",
            "text": "The original's better"
        }
    ]
}